//
//  ContentView.swift
//  Legacy SwiftData sample view kept for reference; not part of the main chat flow.
//
//  Created by Brendan Quinn on 9/12/25.
//

import SwiftUI
import SwiftData

struct ContentView: View {
    // Persisted data context injected by SwiftData runtime.
    @Environment(\.modelContext) private var modelContext
    // Reactive query of all stored Item records.
    @Query private var items: [Item]

    var body: some View {
        // Standard master-detail split view generated by Xcode templates.
        NavigationSplitView {
            List {
                ForEach(items) { item in
                    NavigationLink {
                        // Show details for the selected item.
                        Text("Item at \(item.timestamp, format: Date.FormatStyle(date: .numeric, time: .standard))")
                    } label: {
                        Text(item.timestamp, format: Date.FormatStyle(date: .numeric, time: .standard))
                    }
                }
                .onDelete(perform: deleteItems)
            }
#if os(macOS)
            .navigationSplitViewColumnWidth(min: 180, ideal: 200)
#endif
            .toolbar {
#if os(iOS)
                ToolbarItem(placement: .navigationBarTrailing) {
                    EditButton()
                }
#endif
                ToolbarItem {
                    Button(action: addItem) {
                        Label("Add Item", systemImage: "plus")
                    }
                }
            }
        } detail: {
            Text("Select an item")
        }
    }

    private func addItem() {
        // Insert a new Item row using smooth animation for the list.
        withAnimation {
            let newItem = Item(timestamp: Date())
            modelContext.insert(newItem)
        }
    }

    private func deleteItems(offsets: IndexSet) {
        // Remove selected rows from the SwiftData store.
        withAnimation {
            for index in offsets {
                modelContext.delete(items[index])
            }
        }
    }
}

#Preview {
    // Provide an in-memory model so the preview renders without touching disk data.
    ContentView()
        .modelContainer(for: Item.self, inMemory: true)
}
